#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Franck Labadille
# 2012/08/28
# v0.4
# Licence BSD
#

import sys

import commands
import tools
import models

def get_command(commandlist):
    """Find the command class.

    Returns the class itself or None if not found.

    """
    for attrname in dir(commands):
        if "Command" not in attrname:
            continue
                
        attr = getattr(commands, attrname)

        if hasattr(attr, "command_name"):
            commandlist.append(attr.command_name)
    return commandlist

def get_tool(commandlist):
    """Find the tool class.

    Returns the class itself or None if not found.

    """
    for attrname in dir(tools):
        if "Tool" not in attrname:
            continue

        attr = getattr(tools, attrname)
        
        if hasattr(attr, "tool_name"):
            commandlist.append(attr.tool_name)
    return commandlist

commandlist = []
commandlist = get_tool(commandlist)
commandlist = get_command(commandlist)

for cmd in commandlist:
    print(cmd)
